<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ConvertDataBetweenDataType</AssemblyName>
    <RootNamespace>ConvertDataBetweenDataType</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Radzen.Blazor" Version="5.5.0" />
  </ItemGroup>

</Project>
